# Generated by Django 4.2.18 on 2025-02-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
