# Generated by Django 4.2.18 on 2025-01-28 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_company_name_customuser_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='skills',
        ),
    ]
