# Generated by Django 4.2.18 on 2025-02-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
